#!/bin/bash
if [ $# -lt 3 ]; then
	echo 'usage: rename "*.txt" txt htm'
	exit 0
fi

arg=$1
from=$2
to=$3
for file in `ls $arg`;
do
	#echo $file 
	#echo "echo $file|sed -n s/$from/$to/p"
	newfile=`echo $file|sed -n "s/$from/$to/p"`
	if [ $? -eq 0 ];then
		echo $file --  $newfile
		mv $file $newfile
	else
		echo $file -- failed
	fi
done
